DROP TABLE IF EXISTS sap;

CREATE TABLE sap (
    id          INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    badge_id     INTEGER NOT NULL,
    awarded_at  TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

